export const blindluvAbi = [
  {
    type: "function",
    name: "commitProfile",
    stateMutability: "nonpayable",
    inputs: [{ name: "commitment", type: "bytes32" }],
    outputs: [],
  },
  { type: "function", name: "revokeProfile", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "openSession",
    stateMutability: "nonpayable",
    inputs: [
      { name: "userA", type: "address" },
      { name: "userB", type: "address" },
      { name: "score", type: "uint8" },
      { name: "matchProof", type: "bytes32" },
      { name: "stakeAmount", type: "uint96" },
      { name: "stakeWindow", type: "uint64" },
      { name: "attendanceWindow", type: "uint64" },
    ],
    outputs: [{ name: "sessionId", type: "uint256" }],
  },
  {
    type: "function",
    name: "stake",
    stateMutability: "nonpayable",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmAttendance",
    stateMutability: "nonpayable",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "settle",
    stateMutability: "nonpayable",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelExpired",
    stateMutability: "nonpayable",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getSession",
    stateMutability: "view",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "userA", type: "address" },
          { name: "score", type: "uint8" },
          { name: "status", type: "uint8" },
          { name: "stakedA", type: "bool" },
          { name: "stakedB", type: "bool" },
          { name: "confirmedA", type: "bool" },
          { name: "confirmedB", type: "bool" },
          { name: "userB", type: "address" },
          { name: "stakeAmount", type: "uint96" },
          { name: "matchProof", type: "bytes32" },
          { name: "stakeDeadline", type: "uint64" },
          { name: "attendanceDeadline", type: "uint64" },
          { name: "agent", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "isUnlocked",
    stateMutability: "view",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "hasProfile",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "profileCommitment",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  { type: "function", name: "minStake", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint96" }] },
  { type: "function", name: "stakeToken", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  {
    type: "event",
    name: "SessionOpened",
    inputs: [
      { name: "sessionId", type: "uint256", indexed: true },
      { name: "userA", type: "address", indexed: true },
      { name: "userB", type: "address", indexed: true },
      { name: "agent", type: "address", indexed: false },
      { name: "score", type: "uint8", indexed: false },
      { name: "stakeAmount", type: "uint96", indexed: false },
      { name: "matchProof", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Staked",
    inputs: [
      { name: "sessionId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint96", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SessionUnlocked",
    inputs: [
      { name: "sessionId", type: "uint256", indexed: true },
      { name: "attendanceDeadline", type: "uint64", indexed: false },
    ],
  },
] as const;

/** Minimal USDC surface: ERC-20 plus the EIP-3009 bits x402 needs. */
export const usdcAbi = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "authorizationState",
    stateMutability: "view",
    inputs: [
      { name: "authorizer", type: "address" },
      { name: "nonce", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    // FiatTokenV2_2 bytes-signature overload — the one x402 `exact` uses.
    type: "function",
    name: "transferWithAuthorization",
    stateMutability: "nonpayable",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
      { name: "validAfter", type: "uint256" },
      { name: "validBefore", type: "uint256" },
      { name: "nonce", type: "bytes32" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
] as const;
